### ISSUE TITLE
Detect existing documents

### ISSUE THREAD

**Issue by brgrz** [alexjamesbrown/MongDBIntIdGenerator#4]
I just tried out your generator but it fails when used with a prefilled database. For instance, I migrated some data from RavenDB and it uses integer IDs.

The IDs might be from 1 to some MAX number, with certain IDs missing due to deleted records.

What would be nice is if the generator would perform a sort on integer IDs to find the MAX (last used ID) then start from there (MAX+1).

Do you think this could be implemented and in an atomic fashion?

If so, where should that code go, I might give it a try.

**Comment by alexjamesbrown** [comment]
That wouldn't be atomic...
The only way to accomplish what you're asking would be to update the idCollection with the highest value on import of the old data from Raven

It relies on the findAndModify (which is atomic) to update the count

**Comment by brgrz** [comment]
that's what I did but thought there was another option

**Comment by alexjamesbrown** [comment]
Unfortunately not -
While mongo is querying for the last id in the collection, and returning that to the insert call for the next document, something could alter the collection.
